"""
Gemini LLM client. API key from env GEMINI_API_KEY or backend config.
"""
# from google import genai
import google.genai as genai
from core.config import settings
import re

_client = None

def _get_client():
    global _client
    if _client is None:
        api_key = (settings.GEMINI_API_KEY or "").strip() or None
        _client = genai.Client(api_key=api_key) if api_key else genai.Client()
    return _client

# GEMINI_MODEL = "gemini-2.0-flash"  # or "gemini-3-flash-preview"
GEMINI_MODEL = "gemini-2.5-flash-lite"  # or "gemini-3-flash-preview"

def clean_llm_output(text):
    """
    Remove unwanted characters from LLM response for clean web display
    """
    if not text:
        return text
        
    # Remove markdown symbols (*, _, #, `)
    text = re.sub(r'[*_#`]', '', text)
    
    # Remove multiple spaces
    text = re.sub(r'\s+', ' ', text)
    
    # Remove special characters but keep basic punctuation (. , ! ? - ')
    text = re.sub(r'[^\w\s\.\,\!\?\-\']', '', text)
    
    # Fix common punctuation issues
    text = text.replace(' .', '.').replace(' ,', ',').replace(' !', '!').replace(' ?', '?')
    
    # Remove spaces before punctuation
    text = re.sub(r'\s+([\.\,\!\?\-\'])', r'\1', text)
    
    return text.strip()

def ask_gemini(prompt: str) -> str:
    """Send prompt to Gemini and return response text."""
    api_key = (settings.GEMINI_API_KEY or "").strip()
    if not api_key:
        raise ValueError("GEMINI_API_KEY is not set. Add it to your .env file.")
    
    try:
        client = _get_client()
        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt
        )
        print(f"response generated by the LLM: {response}")
        
        # Get raw response
        raw_response = (response.text or "").strip()
        
        # Clean the response for web display
        cleaned_response = clean_llm_output(raw_response)
        
        print(f"Raw response: {raw_response}")
        print(f"Cleaned response: {cleaned_response}")
        
        return cleaned_response
        
    except Exception as e:
        print(f"[Gemini Error] {str(e)}")
        return "I'm having trouble connecting right now. Please try again."